<h1>Fachbereiche</h1>
<div>
    <a href="<?php echo $this->newUrl; ?>">neuen FB anlegen</a>
</div>
<br/>
<table>
    
    <?php 
        if ($this->fbs->count()>0):
            foreach($this->fbs as $fb): ?>
    <tr>
        <td>
            <?php echo $fb->getValueByKey('opt1text'); ?>
        </td>
        <td>
            <?php echo $fb->getValueByKey('name'); ?>
        </td>
        <td>
            <a href="<?php echo \lw_page::getInstance()->getUrl(array('cmd'=>'editFbForm', "id"=>$fb->getValueByKey('id'), "category_id" => $this->categoryId)); ?>">bearbeiten</a>
        </td>
        <td>
            <?php if($this->deletableSpecification->isSatisfiedBy($fb)): ?>
            <a onclick="return confirm('wirklich löschen?');" href="<?php echo \lw_page::getInstance()->getUrl(array('cmd'=>'deleteFb', "id"=>$fb->getValueByKey('id'), "category_id" => $this->categoryId)); ?>">löschen</a>
            <?php endif; ?>
        </td>
    </tr>
        <?php 
            endforeach; 
        else: ?>
    <div>Keine FB vorhanden!</div>
    <?php endif; ?>
    
</table>